### ISSUE TITLE
Rerender

### ISSUE THREAD

**Issue by mrakitin** [conda-forge/pyisemail-feedstock#1]
@conda-forge-admin, please rerender.

**Comment by mrakitin** [comment]
@conda-forge/core, could you please assist with this feedstock's builds? I don't think any build took place since this feedstock was created. Thanks!

**Comment by ocefpaf** [comment]
Just re-restated the CIs and it should be up soon. See https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=77903

**Comment by mrakitin** [comment]
Thank you @ocefpaf! I don't seem to have permissions to restart builds manually. Is it expected for the feedstock maintainers?

**Comment by ocefpaf** [comment]
You can send a PR with an empty commit. I'm not sure Azure allow us to give maintainers the fine control to restart stuff yet.

**Comment by mrakitin** [comment]
OK, sounds good, it answers the question.

**Comment by jakirkham** [comment]
GitHub’s restart option also works with Azure now.
